FROM node:18-alpine

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install 

# Accept build argument 
ARG VITE_API_URL 
ENV VITE_API_URL=$VITE_API_URL

COPY . . 

RUN npm run build

FROM nginx:alpine 
COPY --from=0 /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
